import typescript from '@rollup/plugin-typescript';
import commonjs from '@rollup/plugin-commonjs';
import { nodeResolve } from '@rollup/plugin-node-resolve';
import nodeGlobals from 'rollup-plugin-node-globals';
import pkg from './package.json';

const input = 'src/webos-tv.ts';

const browserConfig = {
  input,
  output: [
    {
      name: 'webOS',
      file: pkg.browser,
      format: 'iife',
      globals: {
        ws: 'WebSocket',
        url: 'window',
      },
    },
  ],
  plugins: [
    typescript({
      tsconfig: './tsconfig.json',
      // Typings will be generated by the Node build
      declaration: false,
      declarationDir: undefined,
    }),
    commonjs(),
    nodeGlobals({
      process: false,
      buffer: false,
      dirname: false,
      filename: false,
    }),
  ],
};

const nodeConfig = {
  input,
  output: {
    file: pkg.module,
    format: 'es',
  },
  plugins: [
    typescript({ tsconfig: './tsconfig.json' }),
    commonjs(),
    nodeResolve(),
  ],
};

export default [browserConfig, nodeConfig];
